- dwave_networkx/algorithms/coloring.py
- dwave_networkx/algorithms/cover.py
Note this change:
vertex_cover :
-       Iterable of nodes that form a minimum vertex cover, as  determined by the given sampler.
+       Iterable of nodes.
I think this function checks for any vertex cover, not specifically the minimum cover, and the vertices do not have to come from a sampler
> Update docstrings for algos-cover

- dwave_networkx/drawing/chimera_layout.py
- dwave_networkx/drawing/pegasus_layout.py
- dwave_networkx/drawing/qubit_layout.py
- dwave_networkx/drawing/tests/test_chimera_layout.py
- dwave_networkx/drawing/tests/test_pegasus_layout.py
Simple implementation to highlight faults in Chimera or Pegasus graphs.
Example usage:
```
G = dnx.chimera_graph(2, 2, 4, data=False)
G.remove_edges_from([(0,6),(10,13),(26,31)])
G.remove_nodes_from([18,23])
dnx.draw_chimera_yield(G)
plt.show()
```
```
G = dnx.pegasus_graph(3, data=False)
G.remove_edges_from([(5,104),(12,96),(23,112)])
G.remove_nodes_from([109,139])
dnx.draw_pegasus_yield(G)
plt.show()
```
It's also possible to use before a draw_..._embedding() because it differentiates faults with node shape ='x' and edge style = 'dashed'
Also modified description of unused_color which allows color strings and a minor typo in test_chimera_layout.
> Draw qubit graph yield

- dwave_networkx/drawing/qubit_layout.py
Added better colorbar handling. 
before, if there were multiple axes were used for plotting, the colorbar was placed in the same location for all. 
now the colorbar is placed beside the axes itself.
> add better colorbar handling for draw_qubit_graph

- dwave_networkx/generators/pegasus.py
The comment reads like this:
`pegasus_graph(m, fabric_only=True) contains :math:`24m(m-1)-8m` nodes, and`
should this not read:
`pegasus_graph(m, fabric_only=True) contains :math:`24m(m-1)-8(m-1)` nodes, and`
I put 16 into the formula and get 5632 I put 16 into the function and get 5640.
> Error in formula

- dwave_networkx/generators/chimera.py
- dwave_networkx/generators/pegasus.py
- requirements.txt
NetworkX made a backwards compatibility breaking change. I have also tested this change for NetworkX==2.0.
See also:
https://github.com/dwavesystems/dwave-hybrid/issues/211
> Support NetworkX>=2.4

- dwave_networkx/drawing/chimera_layout.py
Oops, this was my bad when I pushed draw_yield(...)
I only caught when I tried using oblong Chimeras... which are not normally used.
> Fix incorrect assignment of columns and rows for draw_yield

- dwave_networkx/drawing/qubit_layout.py
I noticed that using `dnx.draw_chimera` under a `plt.subplot(...)` would fail because of the use of `plt.figure(1)` inside `draw_qubit_graph`.
I think it can be fixed this way.
plt.gcf(): _Get the current figure. If no current figure exists, a new one is created using figure()._
Then, plt.gca() is also necessary. The `cax` is OK as is.
> Use gcf and gca to get/create figure axes in qubit graph

- dwave_networkx/drawing/qubit_layout.py
instead of using only the minimum and maximum values of a given dataset (linear or quadratic biases in this case), if midpoint is provided the colormap will have its middle value at the midpoint
> change the way colormaps created for graph drawing

- dwave_networkx/algorithms/elimination_ordering.py
- dwave_networkx/algorithms/tests/test_canonicalization.py
- dwave_networkx/drawing/chimera_layout.py
- dwave_networkx/drawing/pegasus_layout.py
- dwave_networkx/generators/chimera.py
- dwave_networkx/generators/pegasus.py
- dwave_networkx/generators/tests/test_chimera.py
- dwave_networkx/generators/tests/test_pegasus.py
I got sick of seeing deprecation warnings, so I cleaned out internal functions to avoid them.
> removed calls to deprecated coordinate translators

- dwave_networkx/algorithms/tests/test_tsp.py
- dwave_networkx/algorithms/tsp.py
Constraint on lines 170-171 had quadratic coefficient placed both above and below the diagonal.  Corrected error by dividing coefficient by 2.  Added comments for description.
Resolves #145
> Fix error in QUBO constraint

- dwave_networkx/algorithms/tsp.py
Resolves issue #147 and also addresses issue #103.
There may be a faster way to check route validity, but this will get the job done.
> Update and improve TSP code

- dwave_networkx/drawing/chimera_layout.py
- dwave_networkx/drawing/pegasus_layout.py
- dwave_networkx/drawing/qubit_layout.py
- dwave_networkx/drawing/tests/test_chimera_layout.py
- dwave_networkx/drawing/tests/test_pegasus_layout.py
add an optional overlapped_embedding flag to draw_embedding.
If overlapped_embedding is True, then chains in emb may overlap (contain
the same vertices in G), and the drawing will display these overlaps as
concentric circles.
> add overlapped embedding visualization

- CONTRIBUTING.rst
- README.rst
- docs/LICENSE.txt
- docs/README.rst
- docs/conf.py
- docs/index.rst
- docs/installation.rst
- docs/license.rst
- docs/reference/algorithms/index.rst
- docs/reference/default_sampler.rst
- docs/reference/generators.rst
- docs/reference/index.rst
- docs/sdk_index.rst
Not to be deployed yet. Should fix build warnings on duplicate labels and intersphinx links.
> Reduce warnings in SDK build (for post-unified-docs SDK)

- dwave_networkx/drawing/qubit_layout.py
when evaluating the kwargs.pop even if the existing element is chosen, the fail statement is executed. in this specific example, when 'ax' is sent as None, it will be evaluated to None while still creating a new axis under fig by running the plt.gca() command. The case of ax=None is already handled under the if statements, even though they are very ugly (hardcoded) to make the plots look pretty
> fix double axes bug

- dwave_networkx/drawing/qubit_layout.py
The overlapped_embedding option is hogging the node_size parameter.
This PR allows the user to control it again, if wanted.
> Embedding drawing node size

- dwave_networkx/algorithms/markov.py
Part of short-term doctest fixing for the SDK.
```
Document: docs_dnx/reference/algorithms/generated/dwave_networkx.algorithms.markov.sample_markov_network
--------------------------------------------------------------------------------------------------------
**********************************************************************
File "../../lib/python3.5/site-packages/dwave_networkx/algorithms/markov.py", line ?, in default
Failed example:
samples[0]
Expected:
{'a': 0, 'c': 0, 'b': 0}
Got:
{'a': 0, 'b': 0, 'c': 0}
**********************************************************************
1 items had failures:
1 of  18 in default
18 tests in 1 items.
17 passed and 1 failed.
***Test Failed*** 1 failures.
```
> Fix doctest fail

- dwave_networkx/algorithms/canonicalization.py
- dwave_networkx/algorithms/tests/test_canonicalization.py
Should resolve the broken tests in https://github.com/dwavesystems/dwave-hybrid/pull/222
> Fix canonical_chimera_labeling to correctly choose a root in a corner

- dwave_networkx/algorithms/tests/test_tsp.py
- dwave_networkx/algorithms/tsp.py
This PR fixes #171 .
I first update the test case so that it catches the original bug reported in #171 and then implement the proposed solution from #171 .
> Fix rotation of TSP route to have start in the beginning

- .circleci/config.yml
- docs/conf.py
- docs/requirements.txt
`app.add_stylesheet()` and `app.add_javascript()` were renamed in version 1.8 and obsoleted in version 4
> Update cookie methods  in conf.py

- dwave_networkx/algorithms/tsp.py
- tests/test_tsp.py
Hello,
This is for #203.
It picks up where #200 left off.
I think I've made necessary changes except for some finishing the tests... but I could use a review and feedback :)
> Di graph support

- dwave_networkx/utils/decorators.py
- requirements.txt
- setup.py
Closes https://github.com/dwavesystems/dwave-networkx/issues/212
No longer depend on decorator directly. Newer NetworkX packages also remove their dependency so for those versions it won't be installed at all.
I did remove some of the (IMO) unneeded documentation, but I left the previous implementation more-or-less intact. Probably there is some refactoring that could be done there as well but if it isn't broken...
> Remove direct dependency on decorator package

- .circleci/config.yml
- dwave_networkx/algorithms/markov.py
- requirements.txt
- setup.py
Raise minimum dimod version to 0.10.8
Add dwave-preprocessing as a dependency since it's no longer a dependency of dimod after https://github.com/dwavesystems/dimod/pull/1056
Raise minimum networkx version to 2.4
Should fix the test failures in #211 and #214 .
> Test with python 3.10

- dwave_networkx/drawing/qubit_layout.py
Closes #192.  Replace `DivergingNorm` with `TwoSlopeNorm`.  Not sure exactly what minimum matplotlib we support, but confirmed that this is available in 3.2 (that's where the deprecation started).
> Fix deprecation for DivergingNorm

- dwave_networkx/algorithms/max_cut.py
For consistency with `sampler` docstring, which references use of `set_default_sampler`.
> Add decorator for weighted_maximum_cut

- dwave_networkx/algorithms/elimination_ordering.py
- dwave_networkx/generators/chimera.py
- dwave_networkx/generators/common.py
- dwave_networkx/generators/pegasus.py
- dwave_networkx/generators/zephyr.py
- tests/test_generator_chimera.py
- tests/test_generator_pegasus.py
- tests/test_generator_zephyr.py
Tidied up inaccuracies in docstrings for edge_list and node_list in graph generators. 
Added option for strict topological compliance of edge_list and node_list in these same generators, defaulted to legacy behaviour.
Resolves this bug: https://github.com/dwavesystems/dwave-networkx/issues/222
> Bug fix/documentation

- docs/reference/drawing.rst
- dwave_networkx/drawing/chimera_layout.py
- dwave_networkx/drawing/pegasus_layout.py
- dwave_networkx/drawing/zephyr_layout.py
Copyedit for clarity.
Add reference documentation for the following methods because they were not being generated:
-    chimera_node_placer_2d
-    draw_chimera_embedding
-    draw_chimera_yield
-    draw_pegasus_yield
-    zephyr_node_placer_2d
> Fix typos and styling.

- docs/reference/drawing.rst
Something changed (networkx or matplotlib?) since I created these examples and the 2nd no longer overlays the first (scale mismatch). I'll check if the problem exists in other places too. The updates below produce the expected output:
CC @davage
> Update drawing examples for fixed overlay

- .circleci/config.yml
- README.rst
- requirements.txt
- setup.py
I just test the min and max of the dependency range rather than all the intermediate version. Given the number of dependencies this seems simpler.
> Refresh CI etc

- .circleci/config.yml
It's supposed to route [automatically](https://discuss.circleci.com/t/macos-resource-deprecation-update/46891), but currently we get an error
so specifying it explicitly.
See https://github.com/dwavesystems/dwave-networkx/pull/230#issuecomment-1540586504
> Explicitly specify osx resource class in CI

- dwave_networkx/drawing/qubit_layout.py
- tests/test_qubit_layout.py
For this issue https://github.com/dwavesystems/dwave-networkx/issues/232
> Fix undefined variables for color maps

- .circleci/config.yml
Support for `macos.x86.medium.gen2` is soon to be dropped.
See: https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718
> Use default resource class for macos builds on CircleCi

- README.rst
- docs/bibliography.rst
- docs/index.rst
- docs/reference/algorithms/coloring.rst
- docs/reference/algorithms/cover.rst
- docs/reference/algorithms/elimination_ordering.rst
- docs/reference/algorithms/packing.rst
- dwave_networkx/algorithms/clique.py
- dwave_networkx/algorithms/coloring.py
- dwave_networkx/algorithms/cover.py
- dwave_networkx/algorithms/independent_set.py
- dwave_networkx/algorithms/matching.py
- dwave_networkx/algorithms/social.py
- dwave_networkx/generators/zephyr.py
Part of [sdk](https://github.com/dwavesystems/dwave-ocean-sdk/pull/300) cleanup of build warnings. 
Fixes duplicates on references, [bibliography formatting](https://docs.ocean.dwavesys.com/en/stable/docs_dnx/bibliography.html) problems, and standardizes the index.
> Fix duplicate warnings

- docs/reference/utilities.rst
- dwave_networkx/generators/chimera.py
- dwave_networkx/generators/pegasus.py
- dwave_networkx/generators/zephyr.py
Also, edited those docstrings.
This is the fix for issue https://github.com/dwavesystems/dwave-networkx/issues/234.
Duplicate of #237 because accidentally created PR from `main`.
> Fixed docstrings for graph relabeling and sublattice mapping functionality missing from reference documentation.

- dwave_networkx/generators/chimera.py
- dwave_networkx/generators/pegasus.py
- dwave_networkx/generators/zephyr.py
- tests/test_regular_coloring.py
Colorings of minimal chromatic number on Chimera, Pegasus and Zephyr graphs in the form of a map using the standard coordinate schemes.
> Feature/coloring: Four colorings for Zephyr and Pegasus, and a two coloring for Chimera

- .circleci/config.yml
- dwave_networkx/algorithms/clique.py
- dwave_networkx/generators/chimera.py
- dwave_networkx/generators/pegasus.py
- dwave_networkx/generators/zephyr.py
- requirements.txt
- setup.py
- tests/requirements.txt
We roll the python supported versions window by one here, and refresh the CI in general.
> Drop Python 3.8 and add Python 3.13 support
