dwave_networkx/architectures.py
Signed-off-by: S Davis <myriagon@sddw.net>
=> Fix picayune typos/inconsistencies in comments.  Strictly cosmetic

dwave_networkx/algorithms/elimination_ordering.py, dwave_networkx/algorithms/tests/test_elimination_ordering.py
=> added elimination_order_width with accompanying unittests

dwave_networkx/algorithms/elimination_ordering.py, dwave_networkx/generators/chimera.py
Also working on implementations of pruning strategies (Theorems 6.2,6.3...)
=> Add upper bound as input to treewidth branch and bound

dwave_networkx/exceptions.py, dwave_networkx/utils/decorators.py
@arcondello please review in detail, I made some changes to clarify and added a detailed example because not all users will be adept with decorators
=> Update docstrings, examples for Utilities

dwave_networkx/generators/chimera.py, dwave_networkx/generators/tests/test_chimera.py
=> Fix bug where chimera_graph only accepts integers

docs/reference/drawing.rst
=> Add note to drawing funcs on NumPy, Matplotlib requirements

.coveragerc, .travis.yml, setup.py
* Also update travis to skip superfluous deploys
=> Update setup.py extras to include matplotlib and numpy

dwave_networkx/examples/chimera_graph.py, dwave_networkx/examples/max_cut.py, dwave_networkx/examples/min_maximal_matching.py
3 more examples for dwave_networkx
=> New examples

dwave_networkx/algorithms/coloring.py
@arcondello: example code was missing an import line
=> Add missing import

docs/reference/algorithms/cover.rst, docs/reference/algorithms/packing.rst, docs/reference/algorithms/social.rst, dwave_networkx/algorithms/cover.py, dwave_networkx/algorithms/independent_set.py, dwave_networkx/algorithms/social.py, dwave_networkx/algorithms/tests/test_cover.py, dwave_networkx/algorithms/tests/test_independent_set.py, setup.py
=> WIP: Separate Ising/QUBO construction for some algorithms

dwave_networkx/algorithms/independent_set.py
Added Lagrange parameter to independent_set.py as an optional parameter.
=> Add lagrange

dwave_networkx/algorithms/coloring.py
Hi @JoelPasvolsky 
I added the definition to the docs.  I hope this is okay.
=> Improving documentation for min_vertex_coloring as per issue #64

dwave_networkx/algorithms/TSP.py
Lagrange parameter description was still showing information from max independent set description.
=> updated Larange description

dwave_networkx/generators/pegasus.py, dwave_networkx/generators/tests/test_pegasus.py
- Pegasus fragmentation and de-fragmentation functions. These functions are needed for `dwave-system/embedding/pegasus/find_clique_embedding`
- Note: This PR needs to be merged before dwavesystems/dwave-system#128
@boothby: Please review. Thanks!
=> Refactor pegasus ksample

docs/reference/algorithms/index.rst, docs/reference/algorithms/markov.rst, docs/reference/generators.rst, dwave_networkx/algorithms/__init__.py, dwave_networkx/algorithms/markov.py, dwave_networkx/algorithms/tests/test_markov.py, dwave_networkx/generators/markov.py, dwave_networkx/generators/tests/test_markov.py, setup.py
Based on feedback in https://github.com/dwavesystems/dimod/pull/333
=> Add markov networks

docs/ocean.rst
=> Fix Issue 97

dwave_networkx/generators/pegasus.py
=> added note in pegasus docs to address issue 100

docs/reference/algorithms/tsp.rst, dwave_networkx/algorithms/tests/test_tsp.py, dwave_networkx/algorithms/tsp.py
=> TSP no longer treats the graph as directed

docs/intro.rst
Closes #108 
@gmarsden , @tcnleung
=> Fix pegasus degree 6 --> 15

docs/reference/algorithms/coloring.rst, dwave_networkx/algorithms/coloring.py, dwave_networkx/algorithms/tests/test_coloring.py
Add `vertex_color_qubo(G, colors)` function. We will need to add a `min_vertex_color_qubo(G, chromatic_number=None)` function as well, and then use that in the `min_vertex_color(...)` function. We may as well add a `vertex_color(G, colors, sampler)` function as well.
=> Graph coloring refresh

dwave_networkx/generators/chimera.py, dwave_networkx/generators/tests/test_chimera.py
Added functions for linear_to_chimera and chimera_to_linear index conversion, as well as unit tests.
=> Functionality for converting between linear and chimera indexing.

dwave_networkx/generators/chimera.py, dwave_networkx/generators/pegasus.py, dwave_networkx/generators/tests/test_pegasus.py
Closes #101 
Closes #113 though not with full generality
=> Make relabelling methods more explicit

dwave_networkx/drawing/qubit_layout.py
fix bad midpoint assingment bug. 
Introduce global colormaps if both linear and quadratic biases are provided
fixes #141
=> modify draw_qubit_graph function

docs/reference/algorithms/elimination_ordering.rst, docs/reference/generators.rst, docs/reference/utilities.rst, docs/reference/utilities/index.rst, dwave_networkx/algorithms/elimination_ordering.py, dwave_networkx/generators/chimera.py, dwave_networkx/generators/pegasus.py
@arcondello, you mentioned a few weeks ago that Graph Generators needs some work. Let's talk about this when you're back: https://dnx.readthedocs.io/en/latest/
=> WIP: Generators restructure

dwave_networkx/generators/chimera.py, dwave_networkx/generators/tests/test_chimera.py
=> corrected silly typo in chimera generator, re:issue149

docs/intro.rst, dwave_networkx/algorithms/clique.py
Removes duplicate content post dwavesystems/dwave-ocean-sdk#62
Assumes we agree on proposed structure; alternative is for content to live here and be pulled into SDK top level.
NOT TO BE MERGED BEFORE 62.
=> (Awaiting SDK update) Integrate SDK concepts locally

docs/reference/utilities.rst, docs/reference/utilities/index.rst, dwave_networkx/generators/chimera.py, dwave_networkx/generators/pegasus.py
Also closes https://github.com/dwavesystems/dwave_networkx/issues/166
=> Update coordinate conversions

dwave_networkx/examples/chimera_graph.py
Created PR as part of a tutorial
=> Remove unnecessary comment line

dwave_networkx/examples/min_maximal_matching.py
I did this as part of a tutorial
=> rm unnecesary future import

dwave_networkx/examples/min_vertex_cover.py
=> remove that file

dwave_networkx/examples/max_independent_set.py
I did this as part of a tutorial
=> Remove unnecessary __future__ import

dwave_networkx/algorithms/independent_set.py, tests/test_canonicalization.py, tests/test_chimera_layout.py, tests/test_clique.py, tests/test_decorators.py, tests/test_generator_pegasus.py, tests/test_independent_set.py, tests/test_markov.py, tests/test_pegasus_layout.py, tests/test_tsp.py
=> Update tests to import more consistently

.circleci/config.yml, LICENSE.txt, README.rst, docs/conf.py, docs/index.rst, docs/reference/drawing.rst, docs/sdk_index.rst, dwave_networkx/algorithms/clique.py, dwave_networkx/algorithms/elimination_ordering.py, dwave_networkx/drawing/chimera_layout.py, dwave_networkx/drawing/pegasus_layout.py
test-linux-3.6 fails for rust unrelated to this PR
=> Add link checks

dwave_networkx/algorithms/tsp.py, tests/test_tsp.py
Added a parameter for users to set for missing edge weight penalty in bidirectional TSP problems
=> added new missing edge weight penalty for bidirectional graphs

dwave_networkx/drawing/qubit_layout.py
Tested locally with nx2.4, 2.8.6, 3.1 -- I think we should move the upper-bound on networkx up.
=> Networkx support

docs/bibliography.rst, docs/reference/algorithms/elimination_ordering.rst, dwave_networkx/algorithms/coloring.py, dwave_networkx/algorithms/cover.py, dwave_networkx/algorithms/elimination_ordering.py, dwave_networkx/algorithms/matching.py, dwave_networkx/generators/chimera.py, dwave_networkx/generators/pegasus.py, dwave_networkx/generators/zephyr.py
Update bibliography to match our [system-docs bibliography](https://docs.dwavesys.com/docs/latest/bibliography.html)'s format for citations.
=> Reformat citations for compliance
